### ISSUE TITLE
No auto- slideshow 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_prjmapJS#15]
When each video ends it just restarts instead of advancing to the next one.

**Comment by RELNO** [comment]
@doorleyr did you start the auto slideshow mode [`shift+p`]? 

Note that auto slideshow has fixed interval [for now, a nice feature to have will be video dependent]
You can modify this here: 

```
//autoplay when press P
function autoSlideShow() {
    let interval = 5000;
    alert("Auto slideshow, every " + interval / 1000 + " seconds.");

    var i;
    var slides = document.getElementsByClassName("mySlides");
    //hide all slides divs  at start 
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }

    slideIndex++
    //resert roll to 1 at end 
    if (slideIndex == slides.length) {
        slideIndex = 1
    }

    //set this slide 
    thisSlide = slides[(slideIndex - 1)];

    //reset video at each slide to avoid differences in divs 
    if (thisSlide.querySelector('video')) {
        console.log('video');
        thisSlide.querySelector('video').load();
    }
    thisSlide.style.display = "block";
    // $('#keystoneContainer2').html($(thisSlide).clone());

    if (playing == true) {
        currentTimeout = setTimeout(autoSlideShow, 1000); // Change image every x miliseconds
    }
}
```

**Comment by doorleyr** [comment]
I hadn't pressed SHIFT+p before. However, I just tried that and the alert says 'Stopped auto slideshow', which suggests that the page starts on auto-slideshow mode. 

I also tried pressing SHIFT+p again but when i do that, the video just plays for about a second and then stops and returns to thr start until i press play again. Looking at the code snippet, it looks like the 'interval' variable isn't actually used. It seems to be using the hard-coded 1000:

if (playing == true) {
        currentTimeout = setTimeout(autoSlideShow, 1000); // Change image every x miliseconds
}

**Comment by RELNO** [comment]
Auto play was broken, slideshow should work now: https://github.com/CityScope/CS_prjmapJS/commit/6abeec40e9af466b1084909b95dd2d20cdcbda79
Added also dynamic interval input and button.

**Comment by doorleyr** [comment]
This doesn't work for me. If I load up 2 files and press the Toggle Slideshow button with the default time interval (2 secs), the frame starts rapidly flickering back and forth between the 2 videos. This also happens for other larger intervals I tested such as 11 and 123. Also, on a minor note, if I enter a number with a '0' in it, the fullscreen toggles.

**Comment by RELNO** [comment]
- `2 sec` is a string. 2, however, is an int. You're a hard man to please. 
Getting only num input is apparently a new feature, I've added it but it might break older browsers.  

- Full screen is back to be 'f' and 'f' french keyboards. 

![image](https://user-images.githubusercontent.com/14296774/39948927-2cc74a32-5546-11e8-9d44-f97c4a0ba73d.png)

**Comment by RELNO** [comment]
@doorleyr can we close this?

**Comment by doorleyr** [comment]
I had tried it before with both the string and int formats. That wasn't the issue. Slide show mode still doesn't work at all for me. Seems like we're seeing completely different behaviour. Unlikely it will get solved unless we can sit down together and look at it. I'm now planning to just use a single video file for the Aalto table in Shanghai. Also, for Andorra there's just one file for the table and one for the screen.

**Comment by RELNO** [comment]
OK -- I'm currently don't see issues so I'm closing. We'll test in site later this week and debug as needed.
